### ISSUE TITLE
Doesn't seem to work on iOS

### ISSUE THREAD

**Issue by UtsavPreet** [Ethras/flutter_simple_permissions#1]
-> Installing simple_permissions (0.0.1)
      - Running pre install hooks
    [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: simple_permissions
    
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:116:in `block (2 levels) in verify_framework_usage'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:111:in `each'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:111:in `block in verify_framework_usage'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:108:in `each'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:108:in `verify_framework_usage'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:406:in `validate_targets'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:118:in `install!'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
    /Users/utsav/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
    /Users/utsav/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
    /Users/utsav/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
    /Users/utsav/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
    /Users/utsav/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Error output from CocoaPods:
↳
        [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
    
        export LANG=en_US.UTF-8
        [0m
    
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone X.

**Comment by debuggerx01** [comment]
Hi UtsavPreet , I got the same problem with you , and I found it was caused by when I create my project I NOT made the option of ' swift suppot ' checked.
  Then I fixed my project , by create a new project with the same name with the old in another path , and replace the whole directory name 'ios' in my old project with the one from new project . After that , it all works.
  @Ethras Thank you for your sharing , and maybe you'd better add some tips about that for users ?

**Comment by UtsavPreet** [comment]
Oh, I had also tried doing that. It did work for me only thing was that I thought it wasn't a good solution and that is why opened up an issue here
