### ISSUE TITLE
CocoaPods could not find compatible versions for pod "simple_permissions":

### ISSUE THREAD

**Issue by sabik22** [Ethras/flutter_simple_permissions#10]
How can i solve this?
[!] CocoaPods could not find compatible versions for pod "simple_permissions":
  In snapshot (Podfile.lock):
    simple_permissions (from `Pods/.symlinks/plugins/simple_permissions/ios`)

  In Podfile:
    simple_permissions (from `Pods/.symlinks/plugins/simple_permissions/ios`)

It seems like you've changed the constraints of dependency `simple_permissions` inside your development pod `simple_permissions`.
You should run `pod update simple_permissions` to apply changes you've made.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by Ethras** [comment]
check your Podfile inside your flutter "ios" folder. Uncomment the second line and changed it to
platform :ios, '10.0'

**Comment by hariprasadiit** [comment]
i've facing the same problem and i've to support `ios, 9.0`. is it possible to change `platform :ios, '10.0'` to `platform :ios, '9.0'`? Even flutter is supporting 32 bit ios devices and `ios 8.0`
