### ISSUE TITLE
ios build error (xcode 9 issue?)

### ISSUE THREAD

**Issue by illia-romanenko** [Ethras/flutter_simple_permissions#18]
Good Morning,

when I try to build app for ios it returns following error:

```
/Users/illia/flutter/.pub-cache/hosted/pub.dartlang.org/simple_permissions-0.1.5/ios/Classes/SwiftSimplePermissionsPlugin.swift:219:51: error: incorrect argument label in call (have 'for:', expected 'forMediaType:')
            return AVCaptureDevice.authorizationStatus(for: AVMediaType.audio);
                                                      ^~~~
                                                       forMediaType
    /Users/illia/flutter/.pub-cache/hosted/pub.dartlang.org/simple_permissions-0.1.5/ios/Classes/SwiftSimplePermissionsPlugin.swift:237:51: error: incorrect argument label in call (have 'for:', expected 'forMediaType:')
            return AVCaptureDevice.authorizationStatus(for: AVMediaType.video);
                                                      ^~~~
                                                       forMediaType
    /Users/illia/flutter/.pub-cache/hosted/pub.dartlang.org/simple_permissions-0.1.5/ios/Classes/SwiftSimplePermissionsPlugin.swift:242:38: error: incorrect argument label in call (have 'for:_:', expected 'forMediaType:completionHandler:')
            AVCaptureDevice.requestAccess(for: AVMediaType.video) { response in
                                         ^~~~
                                          forMediaType
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale uk-UA)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by ened** [comment]
@illia-romanenko Looks like the including project is using Swift3, while this project is already using Swift4.

**Comment by illia-romanenko** [comment]
@ened thanks for you reply Sebastian, I think that there is some confusion going on with those packages. 

It appears that example in this repo using just simple_permissions package (not flutter_simple_permissions). Also I noticed that even that on main page Contacts permissions is available it's not available in flutter_simple_permissions (but available in simple_permissions) - or I need to use different pub package?

**Comment by ened** [comment]
The repo is called flutter_simple_permissions, but when you look at https://github.com/Ethras/flutter_simple_permissions/blob/master/pubspec.yaml, you'll find that the name is `simple_permissions`, so I think this is correct.

Did you solve the problem in your project?

**Comment by illia-romanenko** [comment]
I tried to run example from plugin and it worked just fine - maybe that is the other plugin that causes those issues.
