### ISSUE TITLE
Update camera permissions to include `notDetermined` case

### ISSUE THREAD

**Issue by bizz84** [Ethras/flutter_simple_permissions#2]
iOS defines these possible values for the authorization status:

```swift
public enum AVAuthorizationStatus : Int {
    case notDetermined
    case restricted
    case denied
    case authorized
}
```
However, the plugin APIs only return a boolean:

```swift
    private func checkCameraPermission()-> Bool {
        let authStatus = AVCaptureDevice.authorizationStatus(for: AVMediaType.video);
        return authStatus == .authorized;
    }
    
    private func requestCameraPermission(result: @escaping FlutterResult) -> Void {
        AVCaptureDevice.requestAccess(for: AVMediaType.video) { response in
            result(response);
        }
    }
```
This is not enough in some use cases.

For example, I need to show two different UIs depending on whether the status is `notDetermined` or `denied`, and there is no way of doing this currently.

Can the plugin be extended so that it returns an integer that can be mapped to an `enum` across the platform channel in Flutter?

**Comment by Ethras** [comment]
Good point, I'm gonna implement a simple method like getCurrentStatus(Permission permission): StatusEnum
