### ISSUE TITLE
'simple_permissions/simple_permissions-Swift.h' file not found

### ISSUE THREAD

**Issue by aravindhkumar23** [Ethras/flutter_simple_permissions#21]
Did anyone face this issue?  I get stuck with file not found issue.

```
simple_permissions-0.1.5/ios/Classes/SimplePermissionsPlugin.m:2:9: fatal error: 'simple_permissions/simple_permissions-Swift.h' file not found
    #import <simple_permissions/simple_permissions-Swift.h>

```

**Comment by troelsim** [comment]
I'm experiencing the same issue, did you solve this?

**Comment by aravindhkumar23** [comment]
@troelsim Great. Have Fun.

**Comment by leorachit** [comment]
Not working for me.

**Comment by zhou163** [comment]
Check swift when creating a flutter project

**Comment by Gursewak-Uppal** [comment]
Same issue, anyone have solved it?

**Comment by surrenderios** [comment]
try this, works for me
https://github.com/Ethras/flutter_simple_permissions/issues/51#issuecomment-434648578
