### ISSUE TITLE
Pubspec doesn't declare compatibility with Dart 2 #40

### ISSUE THREAD

**Issue by mit-mit** [Ethras/flutter_simple_permissions#23]
The Dart SDK constraints need to be updated to [declare compatibility with Dart 2 stable](https://www.dartlang.org/dart-2#upper-constraints-on-the-sdk-version):

https://github.com/Ethras/flutter_simple_permissions/blob/master/pubspec.yaml#L12

**Comment by mit-mit** [comment]
cc @Ethras

**Comment by Ethras** [comment]
fixed
