### ISSUE TITLE
Any reason for only supporting iOS >= 10.0 ? 

### ISSUE THREAD

**Issue by alancastro** [Ethras/flutter_simple_permissions#24]
It would be useful if it supported iOS >= 8.0 or iOS >= 9.0

**Comment by Ethras** [comment]
it is for one on the permissions but can't remember now which one as I'm really not an iOs developper

**Comment by noordawod** [comment]
I raised the same issue today actually, asking the same question.
So why not add a simple workaround for this in iOS so that support >= 9.0?

Hint: `#if / #else / #endif`
