### ISSUE TITLE
Application won't build after upgrading simple_permissions

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [Ethras/flutter_simple_permissions#37]
After attempting to compile after running Flutter packages upgrade, my app would no longer compile.
I narrowed the issue down by removing the reference to simple_permissions in the pubspec and commenting out the code referring to the class and it compiles now. I was using version 0.1.6. I'm assuming it upgraded to 0.1.7 because I referenced the pub in my pubspec like so:
`    simple_permissions: ^0.1.6`

>  Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
> D8: Program type already present: io.flutter.app.FlutterActivityDelegate$1
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/144.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/146.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/158.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/159.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/160.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/161.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/162.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/168.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/169.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/170.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/171.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/172.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/173.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/174.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/175.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/176.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/177.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/178.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/179.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/180.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/181.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/182.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/183.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/184.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/185.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/186.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/187.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/188.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/189.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/190.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/191.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/192.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/193.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/194.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/195.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/196.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/197.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/198.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/199.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/200.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/201.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/202.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/203.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/205.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/206.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/207.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/208.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/209.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/211.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/212.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/214.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/215.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/216.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/217.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/225.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/226.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/227.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/228.jar, /Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/build/app/intermediates/transforms/dexBuilder/debug/229.jar
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.

and 
 

> Task :app:flutterBuildDebug 
> Running "flutter packages get" in sms_and_contacts_db_importer...      2.0s
> 
>  Task :sms:compileDebugJavaWithJavac 
> Note: /Users/thinkdigital/development/flutter/.pub-cache/hosted/pub.dartlang.org/sms-0.2.2/android/src/main/java/com/babariviere/sms/telephony/TelephonyManager.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 
> /Users/thinkdigital/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0-rc01.aar/4e4414a0a9464b43135aac9b4a52c5eb/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
>     
> /Users/thinkdigital/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0-rc01.aar/4e4414a0a9464b43135aac9b4a52c5eb/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
>     
> error: failed linking references.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Failed to process resources, see aapt output above for details.
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
>         at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
>         at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
>         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> Caused by: org.gradle.tooling.BuildException: Failed to process resources, see aapt output above for details.
>         at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:512)
>         at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.doFullTaskAction(LinkApplicationAndroidResourcesTask.java:249)
>         at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
>         at jdk.internal.reflect.GeneratedMethodAccessor286.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
>         at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
>         at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
>         ... 29 more
>         Suppressed: java.lang.RuntimeException: Some file processing failed, see logs for details
>                 at com.android.builder.internal.aapt.QueuedResourceProcessor.waitForAll(QueuedResourceProcessor.java:121)
>                 at com.android.builder.internal.aapt.QueuedResourceProcessor.end(QueuedResourceProcessor.java:141)
>                 at com.android.bui

**Comment by Tntcommando1** [comment]
I fixed this issue by changing my targetBuildSdk to 28 instead of 27 in my build.gradle

**Comment by ThinkDigitalRepair** [comment]
Hmm. Ok. Thank you.

**Comment by Ethras** [comment]
should be fixed now, compileSdkVersion set to 27
